---
title: "Clean Bike Lane Data"
author: "Liam Purkey"
date: "5/5/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(sf)
library(spData)
library(tmap)
library(purrr)
source("Code/Scripts/utils.R")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  select(-tract_area) %>%
  st_transform(2263)
```

```{r}
#Read bike lane segment data
segment_data = st_read("RawData/NYC_BICYCLE_NETWORK_18D_20200214_p/NYC_BICYCLE_NETWORK_18D_20200214.shp") %>%
  st_transform(2263)
```

#Prepare Data

```{r}
#Join bike lane segments
bikelanes_shp = segment_data %>%
  select(instdate, fromstreet, tostreet) %>% 
  separate(instdate, into = c("year", "month", "time"), sep = "-") %>%
  filter(year <= 2011) %>%
  group_by(fromstreet, tostreet) %>%
  summarize(geometry = st_union(geometry)) %>%
  ungroup()
```

```{r}
#Create centroids
nyc_buffer = st_buffer(st_centroid(nyc_shp), dist = 2640)
```

#Create Intersection Data

```{r}
lane_counts = st_intersection(nyc_buffer, bikelanes_shp) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(n_lanes = n()) %>% 
  right_join(nyc_shp %>% st_drop_geometry(), by = "GEOID") %>%
  mutate(n_lanes = ifelse(is.na(n_lanes), 0, n_lanes))
```

#Write Data

```{r}
write_csv(lane_counts, "CleanData/lane_counts.csv")
```










