---
title: "Calculate Distance to CBD and Wealthy Neighborhoods"
author: "Liam Purkey"
date: "5/24/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(tidycensus)
library(sf)
library(spData)
library(tmap)
library(purrr)
library(furrr)
library(data.table)
source("Code/Scripts/utils.R")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  select(-tract_area) %>%
  st_transform(2263) %>%
  inner_join(
    get_acs(geography = "tract", variables = c(medianincome = "B19013_001"), state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2011, geometry = FALSE) %>%
      select(-NAME, -moe) %>%
  spread(key = "variable", value = "estimate"), by = "GEOID")
  
```

```{r}
#Read in cbd location
cbds = st_read("RawData/nynta_21b/nynta.shp") %>%
  st_transform(2263) %>%
  filter(NTAName %in% c("Midtown-Midtown South", "Battery Park City-Lower Manhattan")) %>%
  select(NTAName) %>%
  st_centroid()
```

#Calculate Distances to Midtown and the Financial District

```{r}
dist_cbds = as.data.frame(clean.units(st_distance(nyc_shp, cbds) / 5280)) %>%
  rename(dist_downtown = V1, dist_midtown = V2) %>%
  cbind(GEOID = nyc_shp$GEOID)
```

#Calculate High Income Neighborhoods and Distance to those Neighborhoods

```{r}
high_income_tracts = nyc_shp %>%
  filter(!grepl("085", GEOID)) %>% 
  filter(ifelse(medianincome > quantile(medianincome, probs = 0.80, na.rm = TRUE), 1, 0) == 1) %>%
  select(-medianincome)
```

```{r}
dist_hi = as.data.frame(cbind(GEOID = nyc_shp$GEOID, dist_hi = apply(clean.units(st_distance(nyc_shp, high_income_tracts))/5280,1, min))) %>%
  mutate(dist_hi = as.numeric(dist_hi))
```

#Join and Write Data

```{r}
dist_data = inner_join(dist_cbds, dist_hi, by = "GEOID")
```

```{r}
write_csv(dist_data, "CleanData/distance_data.csv")
```



