---
title: "Clean Subway Data"
author: "Liam Purkey"
date: "5/5/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(sf)
library(spData)
library(tmap)
library(purrr)
library(stars)
source("Code/Scripts/utils.R")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  select(-tract_area)
```

```{r}
#Read in subway stop data
subway_stops = read_csv("RawData/station_entrances.csv")
```

#Prepare Data

```{r}
#Create subway shapefile
subway_shp = subway_stops %>%
  gather(ID, Line, Route_1:Route_11) %>%
  filter(!is.na(Line)) %>% 
  select(-ID, -Station_Name) %>%
  distinct() %>%
  st_as_sf(coords = c("Station_Longitude", "Station_Latitude"), crs = 4269)
```

```{r}
#Create tract centroids
nyc_centroids = st_centroid(nyc_shp)
```

#Create Subway Count Function

```{r}
aggregate_lines = function(tract, tracts_shp, id_var, lines, line_var) {
  
  tract_shp = tracts_shp %>%
    dplyr::filter(!!as.name(id_var) == tract)
  
  nearby_lines = cbind(lines, distance = clean.units(st_distance(lines, tract_shp))*0.000621371) %>%
    dplyr::filter(distance <= 0.5) %>%
    sf::st_drop_geometry() %>%
    dplyr::distinct(!!as.name(line_var)) %>%
    dplyr::summarize(n_lines = n()) %>%
    mutate(GEOID = as.character(tract))
    
  return(nearby_lines)
  
}
```

#Use purrr:map to create subway counts

```{r}
lines_access = map_dfr(nyc_centroids$GEOID, aggregate_lines, tracts_shp = nyc_centroids, id_var = "GEOID", lines = subway_shp, line_var = "Line")
```

```{r}
map_data = inner_join(nyc_shp, lines_access)
```















