---
title: "Clean NYPD Arrests Data"
author: "Liam Purkey"
date: "5/24/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(data.table)
library(sf)
library(spData)
library(tmap)
library(purrr)
source("Code/Scripts/utils.R")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  select(-tract_area) %>%
  st_transform(2263) %>%
  inner_join(
    get_acs(geography = "tract", variables = c(pop = "B01003_001"), state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2011, geometry = FALSE) %>%
      select(-NAME, -moe) %>%
  spread(key = "variable", value = "estimate"), by = "GEOID")
```

```{r}
#Read in parks shapefile
arrests = fread("RawData/arrests.csv")
```

#Prepare Data

```{r}
arrests_2011 = arrests[!is.na(Latitude) & !is.na(Longitude), .(ARREST_DATE, OFNS_DESC, LAW_CAT_CD, Latitude, Longitude)
        ][,c("month", "day", "year") := tstrsplit(ARREST_DATE, "/", fixed=TRUE)
            ][year == "2011" 
              & (grepl("FELONY ASSAULT|HOMICIDE|MANSLAUGHTER|MURDER|RAPE|ROBBERY", OFNS_DESC) | grepl("BURGLARY", OFNS_DESC) | grepl("DANGEROUS WEAPONS|DRUGS|PROSTITUTION", OFNS_DESC)) 
              ][, crime_type := fcase(grepl("FELONY ASSAULT|HOMICIDE|MANSLAUGHTER|MURDER|RAPE|ROBBERY", OFNS_DESC), "violent",
                                grepl("BURGLARY", OFNS_DESC), "property",
                                grepl("DANGEROUS WEAPONS|DRUGS|PROSTITUTION", OFNS_DESC), "consensual")
                ][, c("ARREST_DATE", "OFNS_DESC", "month", "day", "year") := NULL]
```

```{r}
arrests_2011_shp = arrests_2011 %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4269) %>%
  st_transform(2263)
```

#Aggregate Arrests to Census Tracts

```{r}
crime_counts = st_intersection(nyc_shp, arrests_2011_shp) %>%
  st_drop_geometry() %>%
  group_by(GEOID, crime_type) %>%
  summarize(n_crimes = n()) %>%
  ungroup() %>%
  spread(key = "crime_type", value = "n_crimes") %>%
  right_join(nyc_shp %>% st_drop_geometry(), by = "GEOID") %>%
  replace(is.na(.), 0)
```

#Write Data

```{r}
write_csv(crime_counts, "CleanData/crime_counts.csv")
```






