---
title: "Clean Tree Data"
author: "Liam Purkey"
date: "5/6/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(data.table)
library(sf)
library(spData)
library(tmap)
library(purrr)
library(furrr)
source("Code/Scripts/utils.R")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  st_transform(2263)
```

```{r}
#Read in street tree data 
trees_data = fread("RawData/2005_Street_Tree_Census.csv") 
```

#Prepare Data

```{r}
#Create NYC trees shapefile
trees_shp = trees_data[status == "Excellent" | status == "Good" & longitude != 0 & latitude != 0]
trees_shp = trees_shp %>% st_as_sf(coords = c("longitude", "latitude"), crs = 4269) %>% #Create shapefile with NAD83 Datum
  st_transform(2263) %>% #Transform to NAD83 / New York Long Island
  select(geometry, boroname)  
```

```{r}
#Create borough-specific shapefiles

##Brooklyn
bk_trees = trees_shp %>%
  filter(boroname == "Brooklyn") %>%
  select(geometry)

##Bronx
bx_trees = trees_shp %>%
  filter(boroname == "Bronx") %>%
  select(geometry)

##Manhattan
mn_trees = trees_shp %>%
  filter(boroname == "Manhattan") %>%
  select(geometry)

##Queens
qn_trees = trees_shp %>%
  filter(boroname == "Queens") %>%
  select(geometry)

##Staten Island
si_trees = trees_shp %>%
  filter(boroname == "5") %>%
  select(geometry)
```

#Aggregate Tree Count

```{r}
#Brooklyn
bk_density = st_intersection(nyc_shp %>% filter(grepl("047", as.character(GEOID))), bk_trees) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(d_trees = n() / tract_area) %>%
  ungroup() %>%
  distinct() 

#Bronx
bx_density = st_intersection(nyc_shp %>% filter(grepl("005", as.character(GEOID))), bx_trees) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(d_trees = n() / tract_area) %>%
  ungroup() %>%
  distinct() 

#Manhattan
mn_density = st_intersection(nyc_shp %>% filter(grepl("061", as.character(GEOID))), mn_trees) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(d_trees = n() / tract_area) %>%
  ungroup() %>%
  distinct() 

#Queens
qn_density = st_intersection(nyc_shp %>% filter(grepl("081", as.character(GEOID))), qn_trees) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(d_trees = n() / tract_area) %>%
  ungroup() %>%
  distinct() 

#Staten Island
si_density = st_intersection(nyc_shp %>% filter(grepl("085", as.character(GEOID))), si_trees) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(d_trees = n() / tract_area) %>%
  ungroup() %>%
  distinct() 
```

#Write Tree Data

```{r}
tree_density = bind_rows(bk_density, bx_density) %>%
  bind_rows(mn_density) %>%
  bind_rows(qn_density) %>%
  bind_rows(si_density)
```

```{r}
write_csv(tree_density, "CleanData/tree_density.csv")
```




