---
title: "Clean Parks Data"
author: "Liam Purkey"
date: "5/6/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(sf)
library(spData)
library(tmap)
library(purrr)
source("Code/Scripts/utils.R")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  select(-tract_area) %>%
  st_transform(2263)
```

```{r}
#Read in parks shapefile
parks_shp = st_read("RawData/ARCHIVED\ -\ Parks\ Properties/geo_export_305578e7-67de-47cd-af84-f6770752baff.shp") %>%
  select(geometry) %>%
  st_transform(2263) %>%
  st_make_valid()
```

#Prepare Data

```{r}
#Create buffers
nyc_buffer = st_buffer(st_centroid(nyc_shp), dist = 2640)
```

#Create Intersection Data 

```{r}
park_counts = st_intersection(nyc_buffer, parks_shp) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(n_parks = n()) %>% 
  right_join(nyc_shp %>% st_drop_geometry(), by = "GEOID") %>%
  mutate(n_parks = ifelse(is.na(n_parks), 0, n_parks))
```

#Write Data

```{r}
write_csv(park_counts, "CleanData/park_counts")
```



