---
title: "Clean Housing Maintenance Violations"
author: "Liam Purkey"
date: "5/21/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(tidycensus)
library(sf)
library(spData)
library(tmap)
library(purrr)
library(furrr)
library(data.table)
source("Code/Scripts/utils.R")
```

```{r}
#Read in violations data
violations = fread("RawData/housing_violations.csv")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  select(-tract_area) %>%
  st_transform(2263) %>%
  inner_join(
    get_acs(geography = "tract", variables = c(renter_pop = "B25026_009"), state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2011, geometry = FALSE) %>%
      select(-NAME, -moe) %>%
  spread(key = "variable", value = "estimate"), by = "GEOID")
```

```{r}
#Read in ACS population data
pop_2011 = get_acs(geography = "tract", variables = c(pop = "B01003_001"), state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2011, geometry = FALSE) %>%
  select(-NAME, -moe) %>%
  spread(key = "variable", value = "estimate")
```

#Clean Violations Data

```{r}
violations_2011 = violations[grepl("2011", InspectionDate) & Class != "I" & !(is.na(Latitude) | is.na(Longitude)), .(Class, Latitude, Longitude)]
```

```{r}
violations_shp = violations_2011 %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4269) %>%
  st_transform(2263)
```

```{r}
violations_data = st_intersection(nyc_shp, violations_shp) %>%
  st_drop_geometry() %>%
  group_by(GEOID, Class) %>%
  summarize(violations_pc = n()/renter_pop) %>%
  ungroup() %>%
  distinct(GEOID, Class, violations_pc) %>%
  spread(key = "Class", value = "violations_pc") %>%
  rename(class_a = A, class_b = B, class_c = C) %>%
  right_join(nyc_shp %>% st_drop_geometry() %>% select(GEOID), by = "GEOID") %>%
  replace(is.na(.), 0)
```

#Write Violations Data

```{r}
write_csv(violations_data, "CleanData/violations.csv")
```



