---
title: "Clean WAC Data"
author: "Liam Purkey"
date: "4/27/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(sf)
library(spData)
source("Code/Scripts/utils.R")
```

```{r}
#Read in shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  st_drop_geometry()
```

```{r}
#Read in raw WAC data  
for (year in 2009:2018) {
  
  file_path = paste("RawData/WAC", paste(paste("WAC", year, sep = "_"), "csv", sep = "."), sep = "/")
  data = read_csv(file_path, col_types = cols(GEOID = col_character())) 
  
  if (year == 2009) {
    wac_raw = data 
  } else {
    wac_raw = bind_rows(wac_raw, data)
  }
  
}
```

#Clean WAC Data

```{r}
wac_clean = wac_raw %>%
  inner_join(nyc_shp, by = "GEOID") %>%
  select(year, GEOID, Borough, NTA, tract_area, #Identifiers
         C000, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, #Industry
         CR01, CR02, CR04, CT02, #Race 
         CFA01, CFA02, CFA03, CFA04, CFA05) %>% #Firm Age
  rename(w_total = C000, w_manufacturing = CNS05, w_trade = CNS06, w_retail = CNS07, w_storage = CNS08, 
         w_information = CNS09, w_finance = CNS10, w_realestate = CNS11, w_professional = CNS12, w_management = CNS13,
         w_administrative = CNS14, w_education = CNS15, w_healthcare = CNS16, w_arts = CNS17, w_food = CNS18, w_services = CNS19,
         w_white = CR01, w_black = CR02, w_asian = CR04, w_hispanic = CT02,
         w_last_0_1 = CFA01, w_last_2_3 = CFA02, w_last_4_5 = CFA03, w_last_6_10 = CFA04, w_last_11_plus = CFA05) %>%
  mutate(w_last_5 = w_last_0_1 + w_last_2_3 + w_last_4_5) %>% #Generate counts of jobs at firms aged 0-5
  mutate(w_last_10 = w_last_0_1 + w_last_2_3 + w_last_4_5 + w_last_6_10) %>% #Generate counts of jobs at firms aged 0-10 
  select(-c(w_last_0_1, w_last_2_3, w_last_4_5, w_last_6_10)) %>% #Generate counts of jobs at firms aged 11+ 
  mutate(across(starts_with("w_"), ~.x/w_total, .names = "p_{.col}")) %>% #Normalize job counts by total employment
  mutate(across(starts_with("w_"), ~.x/tract_area, .names = "d_{.col}")) %>% #Normalize job counts by tract area (in square miles)
  select(-starts_with("w_"), -p_w_total, -tract_area) %>% #drop raw job counts and tract area
  balance.panel("GEOID", 10, data = .) #Ensure panel is balanced over the 10-year (2009-2018) period
```

#Write Clean WAC Data

```{r}
write_csv(wac_clean, "CleanData/WAC_clean.csv")
```




