---
title: "Clean Permit Data"
author: "Liam Purkey"
date: "5/18/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load packages
library(magrittr)
library(readxl)
library(readr)
library(tidyverse)
library(sf)
library(spData)
library(tmap)
library(purrr)
library(furrr)
source("Code/Scripts/utils.R")
```

```{r}
#Read in tract shapefile
nyc_shp = st_read("RawData/Boundaries/NewYork.shp") %>%
  st_transform(2263)
```

```{r}
#Read in permit data 
permits_shp = read_csv("RawData/permit_issuances.csv")  %>%
  select(Residential, "Filing Date", LATITUDE, LONGITUDE) %>% 
  filter(Residential == "YES") %>%
  rename(latitude = LATITUDE) %>%
  rename(longitude = LONGITUDE) %>%
  separate(!!as.name("Filing Date"), into = c("month", "day", "year"), sep = "/") %>%
  select(-month, -day, -Residential) %>%
  filter(!is.na(longitude) & !is.na(latitude)) %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4269) %>%
  st_transform(2263)
#Create 2011 permit data
permits_2011_shp = permits_shp %>%
  filter(year == 11)
```

#Aggregate Permits 

##2011

```{r}
permit_counts_2011 = st_intersection(nyc_shp, permits_2011_shp %>% select(geometry)) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(d_permits_2011 = n() / tract_area) %>%
  ungroup() %>%
  distinct() %>%
  right_join(nyc_shp %>% st_drop_geometry() %>% select(GEOID), by = "GEOID") %>%
  mutate(d_permits_2011 = ifelse(is.na(d_permits_2011), 0, d_permits_2011)) 
```

##2009-2011

```{r}
permit_counts = st_intersection(nyc_shp, permits_shp %>% select(geometry)) %>%
  st_drop_geometry() %>%
  group_by(GEOID) %>%
  summarize(d_permits= n() / tract_area) %>%
  ungroup() %>%
  distinct() %>%
  right_join(nyc_shp %>% st_drop_geometry() %>% select(GEOID), by = "GEOID") %>%
  mutate(d_permits = ifelse(is.na(d_permits), 0, d_permits)) 
```

#Join and Write Data

```{r}
permit_data = inner_join(permit_counts, permit_counts_2011, by = "GEOID")
```

```{r}
write_csv(permit_data, "CleanData/permit_density.csv")
```






