---
title: "Collect Tract Boundaries"
author: "Liam Purkey"
date: "4/27/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load Packages
library(magrittr)
library(readxl)
library(readr)
library(tigris)
options(tigris_use_cache = TRUE)
library(sf)
library(spData)
library(tmap)
library(tidycensus)
library(tidyverse)
source("Code/Scripts/utils.R")
```

#Collect New York City Census Tract Shapefile

```{r}
#Collect census tract boundaries
nyc_tracts = get_acs(state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), 
                     year = 2010, geography = "tract", variables = "B01001_001", geometry = TRUE, cb = FALSE) %>%
  select(GEOID, geometry)
```

```{r}
#Collect water boundaries to crop census tract boundaries
nyc_water = area_water(state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), class = "sf")
```

```{r}
#Crop census tract boundaries
nyc_geo = st.erase(nyc_tracts, nyc_water)
```

#Add Census Tract Area Variable

```{r}
nyc_geo = cbind(nyc_geo, tract_area = clean.units(st_area(nyc_geo))*3.86102e-7)
```

#Write Data

```{r}
st_write(nyc_geo, "RawData/Boundaries/NewYork.shp", append=FALSE)
```



