---
title: "Collect ACS Data"
author: "Liam Purkey"
date: "4/27/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load Packages
library(magrittr)
library(readr)
library(readxl)
library(tidycensus)
library(tidyverse)
```

#List Variables to Import

##2011 

```{r}
#Race variables
race_2011 = c(pop = "B01003_001", white_pop = "B02001_002", black_pop = "B02001_003", asian_pop = "B02001_005", hispanic_pop = "B03001_003")

#Education variables 
education_2011 = c(lesshs_pop = "B23006_002", hs_pop = "B23006_009", college_pop = "B23006_023")

#Housing variables 
housing_2011 = c(medianrent = "B25064_001", medianhomevalue = "B25077_001", housing_pop = "B25026_001", renter_pop = "B25026_009")

#Poverty variables 
poverty_2011 = c(poverty_pop = "B17001_002")

#Income variables 
income_2011 = c(medianincome = "B19013_001")

variables_2011 = c(race_2011, education_2011, housing_2011, poverty_2011, income_2011)
```

##2018

```{r}
#Race variables
race_2018 = c(pop = "B01003_001", white_pop = "B02001_002", black_pop = "B02001_003", asian_pop = "B02001_005", hispanic_pop = "B03001_003")

#Education variables
education_2018 = c(lesshs_pop = "B23006_002", hs_pop = "B23006_009", college_pop = "B23006_023")

#Housing variables
housing_2018 = c(medianrent = "B25064_001", medianhomevalue = "B25077_001", housing_pop = "B25026_001", renter_pop = "B25026_009")

#Poverty variables
poverty_2018 = c(poverty_pop = "B17001_002")

#Income variables
income_2018 = c(medianincome = "B19013_001")

variables_2018 = c(race_2018, education_2018, housing_2018, poverty_2018, income_2018)
```

#Import New York Data

```{r}
nyc_2011 = get_acs(geography = "tract", variables = variables_2011, state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2011, geometry = FALSE)
nyc_2018 = get_acs(geography = "tract", variables = variables_2018, state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2018, geometry = FALSE)
```

```{r}
#Format Data
nyc_2011 = nyc_2011 %>%
  select(-c("NAME", "moe")) %>% 
  spread(variable, estimate) %>%
  mutate(year = 2011)
nyc_2018 = nyc_2018 %>%
  select(-c("NAME", "moe")) %>% 
  spread(variable, estimate) %>%
  mutate(year = 2018)
```

#Join and Write Data

```{r}
nyc_data = bind_rows(nyc_2011, nyc_2018)
```

```{r}
write_csv(nyc_data, "RawData/ACS_raw.csv")
```



