---
title: "Create Gentrification Indicator"
author: "Liam Purkey"
date: "4/28/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load Packages
library(magrittr)
library(readr)
library(readxl)
library(Ckmeans.1d.dp)
library(tidycensus)
library(tidyverse)
source("Code/Scripts/utils.R")
```

```{r}
#Read in data used to create gentrification indicator
acs_data = read_csv("CleanData/ACS_clean.csv", col_types = cols(GEOID = col_character())) 
ltdb_data = read_csv("CleanData/LTDB_clean.csv", col_types = cols(GEOID = col_character()))
wac_data = read_csv("CleanData/WAC_clean.csv", col_types = cols(GEOID = col_character()))
```

#Encode Gentrification

##Prepare Data for Gentrification Encoding

```{r}
input_data = acs_data %>% 
  group_by(GEOID) %>%
  mutate(diff_p_college_pop = lead(p_college_pop, order_by = year) - p_college_pop) %>% 
  ungroup() %>%
  filter(year == 2011) %>%
  inner_join(ltdb_data, by = "GEOID") %>% 
  mutate(pre_p_college_pop = p_college_pop - p_college_pop_2000) %>%
  select(GEOID, medianincome, diff_p_college_pop, pre_p_college_pop)
```

##Encode Gentrification given Inputs

```{r}
gen_data = create.gentrification(income_var = "medianincome", college_var = "diff_p_college_pop", pre_var = "pre_p_college_pop",
                                 income_pctile = .5, college_pctile_lower = .5, college_pctile_upper = .75, pre_pctile = .9, data = input_data) %>%
  select(GEOID, gentrify, pre_p_college_pop)
```

#Create Main Datasets

##Create DD Data

```{r}
dd_data = wac_data %>%
  filter(year == 2011 | year == 2018) %>%
  inner_join(gen_data, by = "GEOID") %>%
  inner_join(acs_data %>% filter(year == 2011) %>% select(-year), by = "GEOID")
```

##Create Event Study Data

```{r}
es_data = wac_data %>%
  inner_join(gen_data, by = "GEOID") %>%
  mutate(gentrify = ifelse(year <= 2011, 0, gentrify)) 
```

##Create Summary Statistics Data

```{r}
summary_data = acs_data %>%
  inner_join(gen_data, by = "GEOID") %>%
  inner_join(wac_data, by = c("GEOID", "year")) %>%
  group_by(GEOID) %>%
  mutate(across(starts_with("p_"), ~lead(.x, order_by = year) - .x, .names = "diff_{.col}")) %>%
  mutate(across(starts_with("d_"), ~(lead(.x, order_by = year) - .x)/.x, .names = "pc_{.col}")) %>%
  mutate(across(c(medianhomevalue, medianincome, medianrent, pop), ~(lead(.x, order_by = year) - .x)/.x, .names = "pc_{.col}")) %>%
  ungroup() %>%
  filter(year == 2011)
```

#Write Data

```{r}
write_csv(dd_data, "CleanData/Main/dd_data.csv") #Difference in differences data
write_csv(es_data, "CleanData/Main/es_data.csv") #Event study data
write_csv(summary_data, "CleanData/Main/summary_data.csv") #summary statistics data
```





