---
title: "Create Gentrification Indicator"
author: "Liam Purkey"
date: "4/28/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load Packages
library(magrittr)
library(readr)
library(readxl)
library(Ckmeans.1d.dp)
library(tidycensus)
library(tidyverse)
source("Code/Scripts/utils.R")
```

```{r}
#Read in data used to create gentrification indicator
acs_data = read_csv("CleanData/ACS_clean.csv", col_types = cols(GEOID = col_character())) 
ltdb_data = read_csv("CleanData/LTDB_clean.csv", col_types = cols(GEOID = col_character()))
wac_data = read_csv("CleanData/WAC_clean.csv", col_types = cols(GEOID = col_character()))
```

#Prepare Data for Gentrification Encoding

```{r}
input_data = acs_data %>% 
  group_by(GEOID) %>%
  mutate(diff_p_college_pop = lead(p_college_pop, order_by = year) - p_college_pop) %>% 
  ungroup() %>%
  filter(year == 2011) %>%
  inner_join(ltdb_data, by = "GEOID") %>% 
  mutate(pre_p_college_pop = p_college_pop - p_college_pop_2000) %>%
  select(GEOID, medianincome, diff_p_college_pop, pre_p_college_pop)
```

#Encode Gentrification

```{r}
input_data %>%
  filter(ifelse(medianincome <= median(medianincome), 1, 0) == 1) %>%
  mutate(edugentrify = case_when(diff_p_college_pop <= median(diff_p_college_pop) ~ 0,
                                 diff_p_college_pop >= quantile(diff_p_college_pop, probs = .75) ~ 1)) %>%
  filter(!is.na(edugentrify)) %>%
  filter(ifelse(pre_p_college_pop >= quantile(pre_p_college_pop, probs = .75), 1, 0) == 0) %>%
  group_by(edugentrify) %>%
  summarize(mean = mean(pre_p_college_pop))
```






