---
title: "Collect ACS Data"
author: "Liam Purkey"
date: "4/27/2021"
output: html_document
---

#Setup File

```{r, setup, include=FALSE}
#Change root directory
knitr::opts_knit$set(root.dir = "/Users/liampurkey/Desktop/Research/Gentrification")
```

```{r}
#Load Packages
library(magrittr)
library(lehdr)
library(readxl)
library(tidycensus)
library(tidyverse)
```

#List Variables to Import
```{r}
v17 <- load_variables(2010, "acs5", cache = TRUE)

View(v17)
```

##2010 

```{r}
#Race variables
race_2010 = c(pop = "B01003_001", white = "B02001_002", black = "B02001_003", asian = "B02001_005", hispanic = "B03001_003")

#Age variables 
m_age_2010 = c(m_25_29 = "B01001_011", m_30_34 = "B01001_012", m_35_39 = "B01001_013", m_40_44 = "B01001_014", m_45_49 = "B01001_015", m_50_54 = "B01001_016", 
               m_55_59 = "B01001_017", m_60_64 = "B01001_018")

f_age_2010 = c(f_25_29 = "B01001_035", f_30_34 = "B01001_036", f_35_39 = "B01001_037", f_40_44 = "B01001_038", 
          f_45_49 = "B01001_039", f_50_54 = "B01001_040", f_55_59 = "B01001_041", f_60_64 = "B01001_042")

#Education variables 
education_2010 = c(lesshs_pop = "B23006_002", hs_pop = "B23006_009", college_pop = "B23006_023")

#Housing variables 
housing_2010 = c(medianrent = "B25064_001", medianhomevalue = "B25077_001", housing_pop = "B25026_001", renter_occupied = "B25026_009")

#Poverty variables 
poverty_2010 = c(poverty = "B17001_002")

#Income variables 
income_2010 = c(medianincome = "B19013_001")

variables_2010 = c(race_2010, m_age_2010, f_age_2010, education_2010, housing_2010, poverty_2010, income_2010)
```

##2018

```{r}
#Race variables
race_2018 = c(pop = "B01003_001", white = "B02001_002", black = "B02001_003", asian = "B02001_005", hispanic = "B03001_003")

#Age variables
m_age_2018 = c(m_25_29 = "B01001_011", m_30_34 = "B01001_012", m_35_39 = "B01001_013", m_40_44 = "B01001_014", m_45_49 = "B01001_015", m_50_54 = "B01001_016", 
               m_55_59 = "B01001_017", m_60_61 = "B01001_018", m_62_64 = "B01001_019")

f_age_2018 = c(f_25_29 = "B01001_035", f_30_34 = "B01001_036", f_35_39 = "B01001_037", f_40_44 = "B01001_038", 
               f_45_49 = "B01001_039", f_50_54 = "B01001_040", f_55_59 = "B01001_041", f_60_61 = "B01001_042", f_62_64 = "B01001_043")

#Education variables
education_2018 = c(lesshs_pop = "B23006_002", hs_pop = "B23006_009", college_pop = "B23006_023")

#Housing variables
housing_2018 = c(medianrent = "B25064_001", medianhomevalue = "B25077_001", housing_pop = "B25026_001", renter_occupied = "B25026_009")

#Poverty variables
poverty_2018 = c(poverty = "B17001_002")

#Income variables
income_2018 = c(medianincome = "B19013_001")

variables_2018 = c(race_2018, m_age_2018, f_age_2018, education_2018, housing_2018, poverty_2018, income_2018)
```

#Import New York Data

```{r}
nyc_2010 = get_acs(geography = "tract", variables = variables_2010, state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2010, geometry = FALSE)
nyc_2018 = get_acs(geography = "tract", variables = variables_2018, state = "NY", county = c("Bronx", "Kings", "New York", "Queens", "Richmond"), year = 2018, geometry = FALSE)
```

```{r}
#Format Data
nyc_2010 = nyc_2010 %>%
  select(-c("NAME", "moe")) %>% 
  spread(variable, estimate) %>%
  mutate(year = 2010)
nyc_2018 = nyc_2018 %>%
  select(-c("NAME", "moe")) %>% 
  spread(variable, estimate) %>%
  mutate(year = 2018)
```

#Join and Write Data

```{r}
nyc_data = bind_rows(nyc_2010, nyc_2018)
```

```{r}
write_csv(nyc_data, "RawData/ACS_data.csv")
```



